version: 0.0.1-{build}

image: Visual Studio 2017

clone_depth: 1

environment:
  CONDA: C:\Miniconda36-x64


before_build:
  - cmd: set PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%PATH%
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --add channels bioconda
  - cmd: conda config --add channels csachs
  - cmd: conda update -y conda

build_script:
  - cmd: conda install -y molyso
  - cmd: conda install -y numpy scipy matplotlib nd2file tifffile scikit-image networkx pytables numexpr pandas tunable tqdm
  - cmd: pip install mfisp_boxdetection
  - cmd: python setup.py install
  - cmd: python -m mycelyso
  - cmd: python -V

after_build:
  - cmd: >
          7z
          a
          mycelyso-windows64.zip
          ".appveyor.yml"

artifacts:
  - path: mycelyso-windows64.zip

