version: 0.0.1-{build}

image: Visual Studio 2017

clone_depth: 1

environment:
  CONDA: C:\Miniconda36-x64

cache:
  - C:\Miniconda36-x64\pkgs

before_build:
  - cmd: set PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%PATH%
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --add channels bioconda
  - cmd: conda config --add channels csachs
  - cmd: conda update -y conda
  # unfortunately current pyinstaller in conda does not work with python 3.6
  - cmd: pip install git+https://github.com/pyinstaller/pyinstaller

build_script:
  - cmd: conda install -y molyso
  - cmd: conda install -y numpy scipy matplotlib nd2file tifffile scikit-image networkx pytables numexpr pandas tunable tqdm mfisp-boxdetection
  - cmd: python setup.py install
  - cmd: echo from mycelyso.highlevel.pipeline import Mycelyso > mycelyso.py
  - cmd: "echo if __name__ == '__main__': >> mycelyso.py"
  - cmd: echo     Mycelyso().main() >> mycelyso.py"
  - cmd: pyinstaller mycelyso.py

after_build:
  - cmd: >
          7z
          a
          mycelyso-windows64.zip
          .\dist\mycelyso\*

artifacts:
  - path: mycelyso-windows64.zip

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
