version: 0.0.1-{build}

image: Visual Studio 2017

clone_depth: 1

environment:
  CONDA: C:\Miniconda36-x64


before_build:
  - cmd: set PATH=%PATH%;%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin
  - cmd: conda update -y conda

build_script:
  - cmd: python -V

after_build:
  - cmd: >
          7z
          a
          mycelyso-windows64.zip
          ".appveyor.yml"

artifacts:
  - path: mycelyso-windows64.zip

